# Generated by Django 5.2.1 on 2025-06-24 22:14

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_name', models.CharField(blank=True, max_length=50, null=True)),
                ('default_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_street_address1', models.TextField(blank=True, max_length=20, null=True)),
                ('default_street_address2', models.TextField(blank=True, max_length=20, null=True)),
                ('default_city', models.CharField(blank=True, max_length=100, null=True)),
                ('default_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
