# Generated by Django 5.2.1 on 2025-11-16 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0002_alter_userprofile_default_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be entered in international format (e.g., +63917xxxxxxx) and be between 9 and 15 digits.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
