# Generated by Django 5.2.1 on 2025-11-17 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_account', '0003_alter_userprofile_default_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message="Phone number must be entered in the format:         '+639xxxxxxxxx' or '09xxxxxxxxx'. Up to 13 digits allowed.", regex='^(\\+639|09)\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_postcode',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_postal_code', message='Postal code must be a valid 4-digit Philippine format         (e.g., 1000).', regex='^\\d{4}$')]),
        ),
    ]
