# Generated by Django 5.2.1 on 2025-06-05 18:04

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_phone_number', models.CharField(max_length=15)),
                ('default_email', models.EmailField(max_length=20)),
                ('default_street_address1', models.TextField(max_length=20)),
                ('default_street_address2', models.TextField(max_length=20)),
                ('default_city', models.CharField(max_length=100)),
                ('default_postcode', models.CharField(max_length=20)),
                ('default_country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
