# Generated by Django 5.2.1 on 2025-06-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_default_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
