# Generated by Django 5.2.1 on 2025-06-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_booking_reference_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('REFUND_PENDING', 'Refund Pending (Stripe)'), ('REFUND_PENDING_MANUAL', 'Refund Pending (Manual)'), ('REFUND_FAILED', 'Refund Failed'), ('NO_REFUND', 'No Refund')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed'), ('CANCELLATION_FAILED', 'Cancellation Failed')], default='PENDING', max_length=20),
        ),
    ]
