# Generated by Django 5.2.1 on 2025-06-09 12:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Booking Policy', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of this policy.')),
                ('free_cancellation_cutoff_hours', models.PositiveIntegerField(default=24, help_text='Hours before departure for free cancellation (e.g., 24 means >24h).')),
                ('late_cancellation_cutoff_hours', models.PositiveIntegerField(default=3, help_text='Hours before departure after which no refund is issued for cancellation (e.g., 3 means <=3h).')),
                ('late_cancellation_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Percentage of total price charged for late cancellation (e.g., 0.50 for 50%).', max_digits=5)),
                ('free_rescheduling_cutoff_hours', models.PositiveIntegerField(default=24, help_text='Hours before departure for free rescheduling (e.g., 24 means >24h).')),
                ('late_rescheduling_cutoff_hours', models.PositiveIntegerField(default=3, help_text='Hours before departure after which rescheduling is not allowed (e.g., 3 means <=3h).')),
                ('late_rescheduling_charge_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Percentage of total price charged for late rescheduling (e.g., 0.15 for 15%).', max_digits=5)),
            ],
            options={
                'verbose_name_plural': 'Booking Policies',
            },
        ),
    ]
