# Generated by Django 5.2.1 on 2025-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookingpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount refunded for this booking.', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_status',
            field=models.CharField(choices=[('NONE', 'No Refund Made'), ('PENDING', 'Refund Pending'), ('COMPLETED', 'Refund Completed'), ('FAILED', 'Refund Failed')], default='NONE', help_text='Status of any refunds associated with this booking.', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded'), ('FAILED', 'Payment Failed')], default='PENDING', max_length=30),
        ),
    ]
