# Generated by Django 5.2.1 on 2025-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_refund_amount_booking_refund_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='card_brand',
            field=models.CharField(blank=True, help_text="Brand of the card used (e.g., 'Visa', 'Mastercard', 'Amex').", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='card_last4',
            field=models.CharField(blank=True, help_text='Last four digits of the card used.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method_type',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('GCASH', 'GCash'), ('BANK_TRANSFER', 'Bank_Transfer')], help_text='Type of payment method (e.g., Card, Cash, GCash, Bank Transfer).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, help_text='ID of the Stripe PaymentMethod object used for this booking.', max_length=255, null=True),
        ),
    ]
