# Generated by Django 5.2.1 on 2025-06-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_card_brand_booking_card_last4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_passengers',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method_type',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('GCASH', 'GCash')], help_text='Type of payment method (e.g., Card, Cash, GCash, Bank Transfer).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed'), ('CANCELLATION_FAILED', 'Cancellation Failed')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
