# Generated by Django 5.2.1 on 2025-08-17 16:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_bookingpolicy_offline_payment_cutoff_hours_before_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method_type',
            field=models.CharField(blank=True, choices=[('CARD', 'Card'), ('CASH', 'Cash'), ('GCASH', 'GCash')], help_text='Type of payment method(e.g., Card, Cash, GCash, Bank Transfer).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='free_cancellation_cutoff_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours before departure for free cancellation(e.g., 24 means >24h).'),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='free_rescheduling_cutoff_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours before departure for free rescheduling(e.g., 24 means >24h).'),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='late_cancellation_cutoff_hours',
            field=models.PositiveIntegerField(default=3, help_text='Hours before departure after which no refund is issued forcancellation (e.g., 3 means <=3h).'),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='late_cancellation_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.50'), help_text='Percentage of total price charged for late cancellation(e.g., 0.50 for 50%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='late_rescheduling_charge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Percentage of total price charged for late rescheduling(e.g., 0.15 for 15%).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='late_rescheduling_cutoff_hours',
            field=models.PositiveIntegerField(default=3, help_text='Hours before departure after which rescheduling is notallowed (e.g., 3 means <=3h).'),
        ),
        migrations.AlterField(
            model_name='bookingpolicy',
            name='offline_payment_cutoff_hours_before_departure',
            field=models.PositiveIntegerField(default=6, help_text='Hours before trip departure after which only instant paymentmethods (e.g., Card) are allowed.'),
        ),
    ]
