# Generated by Django 5.2.1 on 2025-08-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_payment_method_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_departure_time',
            field=models.DateTimeField(blank=True, help_text='The departure time of the initial booking. Used for cancellation/rescheduling policy checks.', null=True),
        ),
    ]
