# Generated by Django 5.2.1 on 2025-08-19 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_is_rescheduled_and_more'),
        ('trips', '0006_remove_trip_temp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_from_bookings', to='trips.trip'),
        ),
    ]
