# Generated by Django 5.2.1 on 2025-08-19 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_booking_original_trip'),
        ('trips', '0006_remove_trip_temp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_bookings', to='trips.trip'),
        ),
    ]
