# Generated by Django 5.2.1 on 2025-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_booking_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed'), ('CANCELLATION_FAILED', 'Cancellation Failed'), ('RESCHEDULED', 'Rescheduled')], default='PENDING_PAYMENT', max_length=20),
        ),
    ]
