# Generated by Django 5.2.1 on 2025-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='original_departure_time',
            field=models.DateTimeField(blank=True, help_text='The departure time of the initial booking.        Used for cancellation/rescheduling policy checks.', null=True),
        ),
    ]
