# Generated by Django 5.2.1 on 2025-05-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_number', models.CharField(db_index=True, max_length=30)),
                ('origin', models.CharField(db_index=True, max_length=30)),
                ('destination', models.CharField(db_index=True, max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
            ],
        ),
    ]
