# Generated by Django 5.2.1 on 2025-05-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='total_seats',
        ),
    ]
