# Generated by Django 5.2.1 on 2025-05-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='time',
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(default='23:59', help_text='Expected arrival time (HH:MM)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='bus_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='company_name',
            field=models.CharField(default='BKODA Transport', max_length=100),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(default='00:00', help_text='Expected departure time (HH:MM)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='origin_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
