# Generated by Django 5.2.1 on 2025-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_trip_time_trip_arrival_time_trip_bus_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='temp_field',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
