# Generated by Django 5.2.1 on 2025-05-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='temp_field',
        ),
    ]
